### PR TITLE
Feature : add weekdays to schedule

### PR DESCRIPTION
**Pull request by zzmarty**
Selection on which days the schedule is active. If no days are selected the option is ignored (i.e. schedule works every day).

### CODE REVIEW

**Comment by biddster** [comment]
Looks good, many thanks.

I have a bug fix release to do and then I'll merge it for 0.9.0. 

Only thing that sticks out really is that all days unticked === all days ticked. In most systems, unticking them would disable. However, we have to support existing users where those values don't exist in their node configuration. 

I've never checked to see if NR has a configuration migration option.

**Comment by elyobelyob** [comment]
Looks great, this scheduler is really useful, thanks for building and for anyone adding. Must admit, my technical skills are lacking here to add. But I'm studying the coding.

**Comment by biddster** [comment]
No problem @elyobelyob. If you want to write a node, this is a pretty simple example https://github.com/biddster/node-red-contrib-hs100

**Comment by zzmarty** [comment]
I did an update to support the migration (if the config.[weekdays] are undefined, set default config to true) and set the node to suspend if no weekdays are ticked, which seems more logical.
However this code now has some merge conflicts, so I'll let it rest until the new version and than re-apply.

**Comment by biddster** [comment]
Thanks for the update @zzmarty. Had a busy week so will look to merge it tomorrow (I hope). Many thanks again for the contribution, it's really appreciated.

**Comment by biddster** [comment]
Thanks for the contribution @zzmarty. Sorry it took so long for me to merge. I've got it in test here prior to release.

**Pull request merged**
